version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-bullseye
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    restart: unless-stopped
    ports:
      - 4200:4200
      - 3333:3333

